import 'technology.dart';

class TechRegistry {
  static const List<SosTechnology> all = [
    SosTechnology(
      id: 'mesh_overlay',
      name: 'Mesh Overlay (Promiscuous Forwarding)',
      category: TechnologyCategory.mesh,
      status: TechnologyStatus.supported,
      summary: 'Encaminhamento por flooding baseado em IDs, sem depender de IP.',
      protocols: ['SosEnvelope', 'SosFrame'],
      platforms: ['mobile', 'desktop', 'tv', 'wear', 'web', 'java'],
    ),
    SosTechnology(
      id: 'wifi_direct_mdns_tcp',
      name: 'WiFi Direct / LAN TCP + mDNS',
      category: TechnologyCategory.lan,
      status: TechnologyStatus.supported,
      summary: 'Descoberta LAN via mDNS e transporte TCP (Wi-Fi/Ethernet).',
      protocols: ['mDNS', 'TCP'],
      platforms: ['mobile', 'desktop', 'tv', 'wear', 'java'],
    ),
    SosTechnology(
      id: 'ethernet_lan',
      name: 'Ethernet LAN',
      category: TechnologyCategory.lan,
      status: TechnologyStatus.supported,
      summary: 'Transporte LAN sobre TCP/IP físico.',
      protocols: ['TCP'],
      platforms: ['desktop', 'server', 'java'],
    ),
    SosTechnology(
      id: 'lan_poe',
      name: 'Power over Ethernet (PoE)',
      category: TechnologyCategory.lan,
      status: TechnologyStatus.planned,
      summary: 'Alimentacao eletrica via cabos Ethernet.',
      protocols: ['IEEE 802.3af', '802.3at', '802.3bt'],
    ),
    SosTechnology(
      id: 'bluetooth_le',
      name: 'Bluetooth LE',
      category: TechnologyCategory.lan,
      status: TechnologyStatus.supported,
      summary: 'BLE completo com advertising, scanning e GATT.',
      protocols: ['GATT'],
      platforms: ['mobile', 'wear', 'desktop'],
    ),
    SosTechnology(
      id: 'bluetooth_classic',
      name: 'Bluetooth Classic',
      category: TechnologyCategory.lan,
      status: TechnologyStatus.supported,
      summary: 'RFCOMM/BR-EDR implementado com descoberta e conexao automatica.',
      protocols: ['RFCOMM'],
      platforms: ['mobile', 'desktop'],
    ),
    SosTechnology(
      id: 'bluetooth_mesh',
      name: 'Bluetooth Mesh',
      category: TechnologyCategory.mesh,
      status: TechnologyStatus.supported,
      summary: 'Mesh BLE implementado com provisioning e relay.',
      protocols: ['GATT', 'Mesh Provisioning'],
      platforms: ['mobile', 'wear'],
    ),
    SosTechnology(
      id: 'wifi_4',
      name: 'WiFi 4 (802.11n)',
      category: TechnologyCategory.wifi,
      status: TechnologyStatus.supported,
      summary: 'Conectividade WiFi via stack do sistema (dependente de hardware).',
    ),
    SosTechnology(
      id: 'wifi_5',
      name: 'WiFi 5 (802.11ac)',
      category: TechnologyCategory.wifi,
      status: TechnologyStatus.supported,
      summary: 'Conectividade WiFi via stack do sistema (dependente de hardware).',
    ),
    SosTechnology(
      id: 'wifi_6',
      name: 'WiFi 6 (802.11ax)',
      category: TechnologyCategory.wifi,
      status: TechnologyStatus.supported,
      summary: 'Conectividade WiFi via stack do sistema (dependente de hardware).',
    ),
    SosTechnology(
      id: 'wifi_6e',
      name: 'WiFi 6E',
      category: TechnologyCategory.wifi,
      status: TechnologyStatus.supported,
      summary: 'Conectividade WiFi via stack do sistema (dependente de hardware).',
    ),
    SosTechnology(
      id: 'wifi_7',
      name: 'WiFi 7 (802.11be)',
      category: TechnologyCategory.wifi,
      status: TechnologyStatus.experimental,
      summary: 'WiFi 7 emergente.',
    ),
    SosTechnology(
      id: 'wifi_fast_roaming',
      name: 'WiFi Fast Roaming (802.11k/v/w)',
      category: TechnologyCategory.wifi,
      status: TechnologyStatus.planned,
      summary: 'Roaming rapido entre APs com 802.11k/v/w.',
    ),
    SosTechnology(
      id: 'wifi_direct',
      name: 'WiFi Direct',
      category: TechnologyCategory.wifi,
      status: TechnologyStatus.supported,
      summary: 'Descoberta LAN via mDNS (Wi-Fi/Ethernet).',
    ),
    SosTechnology(
      id: 'lifi_vlc',
      name: 'Li-Fi / VLC',
      category: TechnologyCategory.optical,
      status: TechnologyStatus.planned,
      summary: 'Comunicacao por luz visivel.',
    ),
    SosTechnology(
      id: 'zigbee',
      name: 'Zigbee',
      category: TechnologyCategory.iot,
      status: TechnologyStatus.planned,
      summary: 'Mesh IoT de baixa potencia.',
      requirements: ['hardware zigbee'],
    ),
    SosTechnology(
      id: 'thread',
      name: 'Thread',
      category: TechnologyCategory.iot,
      status: TechnologyStatus.planned,
      summary: 'Rede mesh IP para IoT.',
      requirements: ['hardware thread'],
    ),
    SosTechnology(
      id: 'matter',
      name: 'Matter',
      category: TechnologyCategory.iot,
      status: TechnologyStatus.planned,
      summary: 'Padrao interoperavel para smart home.',
    ),
    SosTechnology(
      id: 'z_wave',
      name: 'Z-Wave',
      category: TechnologyCategory.iot,
      status: TechnologyStatus.planned,
      summary: 'IoT de curta distancia.',
      requirements: ['hardware z-wave'],
    ),
    SosTechnology(
      id: 'nfc',
      name: 'NFC',
      category: TechnologyCategory.lan,
      status: TechnologyStatus.planned,
      summary: 'Troca curta distancia.',
    ),
    SosTechnology(
      id: 'uwb',
      name: 'UWB',
      category: TechnologyCategory.lan,
      status: TechnologyStatus.planned,
      summary: 'Localizacao e comunicacao curta.',
      requirements: ['hardware uwb'],
    ),
    SosTechnology(
      id: 'sixlowpan',
      name: '6LoWPAN',
      category: TechnologyCategory.iot,
      status: TechnologyStatus.planned,
      summary: 'IPv6 em redes de baixa potencia.',
    ),
    SosTechnology(
      id: 'wsn',
      name: 'Wireless Sensor Networks',
      category: TechnologyCategory.emerging,
      status: TechnologyStatus.planned,
      summary: 'Malha de sensores sem fio.',
    ),
    SosTechnology(
      id: 'cell_2g_gsm',
      name: '2G GSM',
      category: TechnologyCategory.cellular,
      status: TechnologyStatus.planned,
      summary: 'Rede celular legada.',
    ),
    SosTechnology(
      id: 'cell_2g_cdma',
      name: '2G CDMA',
      category: TechnologyCategory.cellular,
      status: TechnologyStatus.planned,
      summary: 'Rede celular legada.',
    ),
    SosTechnology(
      id: 'cell_2g_tdma',
      name: '2G TDMA (IS-136)',
      category: TechnologyCategory.cellular,
      status: TechnologyStatus.planned,
      summary: 'Rede celular TDMA legada.',
    ),
    SosTechnology(
      id: 'cell_2g_pdc',
      name: '2G PDC',
      category: TechnologyCategory.cellular,
      status: TechnologyStatus.planned,
      summary: 'Padrao celular japones legado.',
    ),
    SosTechnology(
      id: 'cell_3g_umts',
      name: '3G UMTS/WCDMA',
      category: TechnologyCategory.cellular,
      status: TechnologyStatus.planned,
      summary: 'Rede celular 3G.',
    ),
    SosTechnology(
      id: 'cell_3g_hspa',
      name: '3G HSPA/HSPA+',
      category: TechnologyCategory.cellular,
      status: TechnologyStatus.planned,
      summary: 'Evolucao de dados do UMTS.',
    ),
    SosTechnology(
      id: 'cell_3g_evdo',
      name: '3G EVDO/CDMA2000',
      category: TechnologyCategory.cellular,
      status: TechnologyStatus.planned,
      summary: 'Rede celular 3G.',
    ),
    SosTechnology(
      id: 'cell_3g_td_scdma',
      name: '3G TD-SCDMA',
      category: TechnologyCategory.cellular,
      status: TechnologyStatus.planned,
      summary: 'Padrao 3G usado na China.',
    ),
    SosTechnology(
      id: 'cell_4g_lte',
      name: '4G LTE',
      category: TechnologyCategory.cellular,
      status: TechnologyStatus.planned,
      summary: 'Rede celular 4G.',
    ),
    SosTechnology(
      id: 'cell_4g_lte_a',
      name: 'LTE-A / LTE-A Pro',
      category: TechnologyCategory.cellular,
      status: TechnologyStatus.planned,
      summary: 'Evolucao 4G.',
    ),
    SosTechnology(
      id: 'cell_5g_nr',
      name: '5G NR',
      category: TechnologyCategory.cellular,
      status: TechnologyStatus.planned,
      summary: 'Rede celular 5G.',
    ),
    SosTechnology(
      id: 'cell_5g_mmwave',
      name: '5G mmWave',
      category: TechnologyCategory.cellular,
      status: TechnologyStatus.planned,
      summary: '5G em ondas milimetricas.',
    ),
    SosTechnology(
      id: 'cell_5g_advanced',
      name: '5G Advanced',
      category: TechnologyCategory.cellular,
      status: TechnologyStatus.experimental,
      summary: 'Evolucao 5G.',
    ),
    SosTechnology(
      id: 'cell_6g',
      name: '6G / IMT-2030',
      category: TechnologyCategory.cellular,
      status: TechnologyStatus.experimental,
      summary: 'Pesquisa 6G.',
    ),
    SosTechnology(
      id: 'cell_ltem',
      name: 'LTE-M',
      category: TechnologyCategory.cellular,
      status: TechnologyStatus.planned,
      summary: 'IoT celular baixo consumo.',
    ),
    SosTechnology(
      id: 'cell_nbiot',
      name: 'NB-IoT',
      category: TechnologyCategory.cellular,
      status: TechnologyStatus.planned,
      summary: 'IoT celular narrowband.',
    ),
    SosTechnology(
      id: 'open_ran',
      name: 'Open RAN / vRAN',
      category: TechnologyCategory.cellular,
      status: TechnologyStatus.planned,
      summary: 'Arquitetura aberta de RAN.',
    ),
    SosTechnology(
      id: 'sat_geo',
      name: 'Satélite GEO',
      category: TechnologyCategory.satellite,
      status: TechnologyStatus.planned,
      summary: 'Comunicacao geoestacionaria.',
      requirements: ['terminal satelite'],
    ),
    SosTechnology(
      id: 'sat_meo',
      name: 'Satélite MEO',
      category: TechnologyCategory.satellite,
      status: TechnologyStatus.planned,
      summary: 'Comunicacao orbita media.',
      requirements: ['terminal satelite'],
    ),
    SosTechnology(
      id: 'sat_leo',
      name: 'Satélite LEO',
      category: TechnologyCategory.satellite,
      status: TechnologyStatus.planned,
      summary: 'Comunicacao orbita baixa.',
      requirements: ['terminal satelite'],
    ),
    SosTechnology(
      id: 'sat_ntn_3gpp',
      name: '3GPP NTN (Non-Terrestrial Networks)',
      category: TechnologyCategory.satellite,
      status: TechnologyStatus.planned,
      summary: 'Padrao 3GPP para redes nao-terrestres.',
      protocols: ['3GPP Release 17+'],
    ),
    SosTechnology(
      id: 'sat_lband',
      name: 'Satélite Banda L',
      category: TechnologyCategory.satellite,
      status: TechnologyStatus.planned,
      summary: 'Servicos L-band (Iridium/Inmarsat).',
      requirements: ['terminal satelite'],
    ),
    SosTechnology(
      id: 'sat_d2d',
      name: 'Direct-to-Device',
      category: TechnologyCategory.satellite,
      status: TechnologyStatus.planned,
      summary: 'Satélite direto para dispositivos.',
      requirements: ['modem satelital'],
    ),
    SosTechnology(
      id: 'sat_cubesat',
      name: 'CubeSat',
      category: TechnologyCategory.satellite,
      status: TechnologyStatus.experimental,
      summary: 'Satélites pequenos.',
    ),
    SosTechnology(
      id: 'sat_haps',
      name: 'HAPS',
      category: TechnologyCategory.satellite,
      status: TechnologyStatus.experimental,
      summary: 'Plataformas de alta altitude.',
    ),
    SosTechnology(
      id: 'sat_6g',
      name: '6G via Satélite',
      category: TechnologyCategory.satellite,
      status: TechnologyStatus.experimental,
      summary: 'Integração satélite-terrestre para 6G.',
    ),
    SosTechnology(
      id: 'sat_starlink',
      name: 'Starlink',
      category: TechnologyCategory.satellite,
      status: TechnologyStatus.planned,
      summary: 'Constelacao LEO banda larga.',
      requirements: ['terminal starlink'],
    ),
    SosTechnology(
      id: 'sat_oneweb',
      name: 'OneWeb',
      category: TechnologyCategory.satellite,
      status: TechnologyStatus.planned,
      summary: 'Constelacao LEO.',
      requirements: ['terminal oneweb'],
    ),
    SosTechnology(
      id: 'sat_iot',
      name: 'Satellite IoT',
      category: TechnologyCategory.satellite,
      status: TechnologyStatus.planned,
      summary: 'IoT via satelite.',
      requirements: ['modem satelital'],
    ),
    SosTechnology(
      id: 'sat_qkd',
      name: 'Satellite QKD',
      category: TechnologyCategory.satellite,
      status: TechnologyStatus.experimental,
      summary: 'Distribuicao quantica de chaves via satelite.',
    ),
    SosTechnology(
      id: 'sat_hybrid_leo_geo',
      name: 'LEO-GEO Hybrid Networks',
      category: TechnologyCategory.satellite,
      status: TechnologyStatus.experimental,
      summary: 'Integração LEO + GEO para cobertura global.',
    ),
    SosTechnology(
      id: 'radio_am',
      name: 'Radio AM',
      category: TechnologyCategory.radio,
      status: TechnologyStatus.planned,
      summary: 'Radiodifusao AM.',
    ),
    SosTechnology(
      id: 'radio_fm',
      name: 'Radio FM',
      category: TechnologyCategory.radio,
      status: TechnologyStatus.planned,
      summary: 'Radiodifusao FM.',
    ),
    SosTechnology(
      id: 'radio_dab',
      name: 'DAB/DAB+',
      category: TechnologyCategory.radio,
      status: TechnologyStatus.planned,
      summary: 'Radio digital.',
    ),
    SosTechnology(
      id: 'radio_drm',
      name: 'DRM/DRM+',
      category: TechnologyCategory.radio,
      status: TechnologyStatus.planned,
      summary: 'Digital Radio Mondiale.',
    ),
    SosTechnology(
      id: 'radio_internet_streaming',
      name: 'Rádio por Internet/Streaming',
      category: TechnologyCategory.radio,
      status: TechnologyStatus.planned,
      summary: 'Broadcast via HTTP/RTMP/HLS.',
      protocols: ['HTTP', 'RTMP', 'HLS'],
    ),
    SosTechnology(
      id: 'radio_ham_hf',
      name: 'Radio Amador HF',
      category: TechnologyCategory.radio,
      status: TechnologyStatus.planned,
      summary: 'Radio HF emergencia.',
      requirements: ['transceptor HF'],
    ),
    SosTechnology(
      id: 'radio_ham_vhf',
      name: 'Radio Amador VHF',
      category: TechnologyCategory.radio,
      status: TechnologyStatus.planned,
      summary: 'Radio VHF.',
      requirements: ['transceptor VHF'],
    ),
    SosTechnology(
      id: 'radio_ham_uhf',
      name: 'Radio Amador UHF',
      category: TechnologyCategory.radio,
      status: TechnologyStatus.planned,
      summary: 'Radio UHF.',
      requirements: ['transceptor UHF'],
    ),
    SosTechnology(
      id: 'radio_digital_modes',
      name: 'Rádio Amador Digital (D-STAR/DMR/Fusion/NXDN)',
      category: TechnologyCategory.radio,
      status: TechnologyStatus.planned,
      summary: 'Modos digitais para radioamador.',
      protocols: ['D-STAR', 'DMR', 'Fusion', 'NXDN'],
    ),
    SosTechnology(
      id: 'radio_aviation_vhf',
      name: 'VHF Aviação',
      category: TechnologyCategory.radio,
      status: TechnologyStatus.planned,
      summary: 'Comunicação VHF aeronáutica.',
    ),
    SosTechnology(
      id: 'radio_pmr_gmrs',
      name: 'PMR/GMRS',
      category: TechnologyCategory.radio,
      status: TechnologyStatus.planned,
      summary: 'Radio comunicacao curta distancia.',
    ),
    SosTechnology(
      id: 'radio_cb',
      name: 'CB Radio',
      category: TechnologyCategory.radio,
      status: TechnologyStatus.planned,
      summary: 'Citizens Band.',
    ),
    SosTechnology(
      id: 'lpwan_lora',
      name: 'LoRa / LoRaWAN',
      category: TechnologyCategory.radio,
      status: TechnologyStatus.supported,
      summary: 'LoRa implementado via serial com AT commands.',
      protocols: ['LoRaWAN', 'Serial AT'],
      platforms: ['desktop', 'server'],
    ),
    SosTechnology(
      id: 'lpwan_sigfox',
      name: 'Sigfox',
      category: TechnologyCategory.radio,
      status: TechnologyStatus.planned,
      summary: 'LPWAN Sigfox.',
      requirements: ['operadora sigfox'],
    ),
    SosTechnology(
      id: 'lpwan_weightless',
      name: 'Weightless',
      category: TechnologyCategory.radio,
      status: TechnologyStatus.experimental,
      summary: 'LPWAN Weightless.',
    ),
    SosTechnology(
      id: 'microwave_p2p',
      name: 'Microwave Ponto-a-Ponto',
      category: TechnologyCategory.radio,
      status: TechnologyStatus.planned,
      summary: 'Backhaul micro-ondas.',
      requirements: ['antenas micro-ondas'],
    ),
    SosTechnology(
      id: 'vhf_sar',
      name: 'VHF/UHF Busca e Resgate',
      category: TechnologyCategory.radio,
      status: TechnologyStatus.planned,
      summary: 'Comunicacao VHF/UHF para SAR.',
    ),
    SosTechnology(
      id: 'hf_emergency',
      name: 'HF Emergencia',
      category: TechnologyCategory.radio,
      status: TechnologyStatus.planned,
      summary: 'Comunicacao HF de emergencia.',
    ),
    SosTechnology(
      id: 'plc_narrowband',
      name: 'PLC Narrowband',
      category: TechnologyCategory.plc,
      status: TechnologyStatus.planned,
      summary: 'PLC narrowband.',
      requirements: ['modem PLC'],
    ),
    SosTechnology(
      id: 'plc_g3',
      name: 'PLC G3',
      category: TechnologyCategory.plc,
      status: TechnologyStatus.planned,
      summary: 'PLC G3 smart grid.',
      requirements: ['modem PLC G3'],
    ),
    SosTechnology(
      id: 'plc_prime',
      name: 'PLC PRIME',
      category: TechnologyCategory.plc,
      status: TechnologyStatus.planned,
      summary: 'PLC PRIME smart grid.',
      requirements: ['modem PLC PRIME'],
    ),
    SosTechnology(
      id: 'plc_bpl',
      name: 'PLC Broadband (BPL)',
      category: TechnologyCategory.plc,
      status: TechnologyStatus.planned,
      summary: 'PLC banda larga.',
      requirements: ['modem PLC BPL'],
    ),
    SosTechnology(
      id: 'plc_ghn',
      name: 'ITU-T G.hn',
      category: TechnologyCategory.plc,
      status: TechnologyStatus.planned,
      summary: 'PLC convergente.',
    ),
    SosTechnology(
      id: 'plc_homeplug',
      name: 'HomePlug AV/AV2',
      category: TechnologyCategory.plc,
      status: TechnologyStatus.planned,
      summary: 'PLC residencial.',
    ),
    SosTechnology(
      id: 'plc_ami',
      name: 'Smart Grid AMI',
      category: TechnologyCategory.plc,
      status: TechnologyStatus.planned,
      summary: 'Infraestrutura de medição avançada.',
      protocols: ['PLC G3', 'PRIME'],
    ),
    SosTechnology(
      id: 'plc_hybrid_rf',
      name: 'Hybrid PLC-RF',
      category: TechnologyCategory.plc,
      status: TechnologyStatus.experimental,
      summary: 'PLC combinado com RF (LoRa/NB-IoT).',
    ),
    SosTechnology(
      id: 'plc_thz',
      name: 'PLC Terahertz',
      category: TechnologyCategory.plc,
      status: TechnologyStatus.experimental,
      summary: 'PLC em bandas THz (pesquisa).',
    ),
    SosTechnology(
      id: 'plc_dc_distribution',
      name: 'PLC em Distribuição DC',
      category: TechnologyCategory.plc,
      status: TechnologyStatus.experimental,
      summary: 'PLC aplicado em redes DC e datacenters.',
    ),
    SosTechnology(
      id: 'acoustic_voice',
      name: 'Comunicacao Acustica (voz)',
      category: TechnologyCategory.acoustic,
      status: TechnologyStatus.planned,
      summary: 'Voz e audio.',
    ),
    SosTechnology(
      id: 'acoustic_ultrasound',
      name: 'Ultrassom',
      category: TechnologyCategory.acoustic,
      status: TechnologyStatus.planned,
      summary: 'Comunicacao ultrassonica.',
    ),
    SosTechnology(
      id: 'acoustic_underwater',
      name: 'Modem Acustico Subaquatico',
      category: TechnologyCategory.acoustic,
      status: TechnologyStatus.planned,
      summary: 'Comunicacao subaquatica.',
    ),
    SosTechnology(
      id: 'acoustic_sonar',
      name: 'Sonar Acústico',
      category: TechnologyCategory.acoustic,
      status: TechnologyStatus.planned,
      summary: 'Detecção e navegação via sonar.',
    ),
    SosTechnology(
      id: 'acoustic_hydro_modem',
      name: 'Hydroacoustic Data Modems',
      category: TechnologyCategory.acoustic,
      status: TechnologyStatus.planned,
      summary: 'Modems hidroacusticos para dados.',
    ),
    SosTechnology(
      id: 'acoustic_usbl',
      name: 'USBL (Posicionamento Subaquático)',
      category: TechnologyCategory.acoustic,
      status: TechnologyStatus.planned,
      summary: 'Localizacao subaquatica ultra-short baseline.',
    ),
    SosTechnology(
      id: 'acoustic_structure_vibration',
      name: 'Vibração em Estruturas',
      category: TechnologyCategory.acoustic,
      status: TechnologyStatus.experimental,
      summary: 'Comunicacao via vibracoes estruturais.',
    ),
    SosTechnology(
      id: 'acoustic_janus',
      name: 'JANUS (NATO)',
      category: TechnologyCategory.acoustic,
      status: TechnologyStatus.planned,
      summary: 'Padrao subaquatico.',
    ),
    SosTechnology(
      id: 'acoustic_haptic',
      name: 'Comunicacao Haptica',
      category: TechnologyCategory.acoustic,
      status: TechnologyStatus.planned,
      summary: 'Vibracao/estrutura.',
    ),
    SosTechnology(
      id: 'opt_fiber_smf',
      name: 'Fibra Optica SMF',
      category: TechnologyCategory.optical,
      status: TechnologyStatus.planned,
      summary: 'Fibra monomodo.',
    ),
    SosTechnology(
      id: 'opt_fiber_mmf',
      name: 'Fibra Optica MMF',
      category: TechnologyCategory.optical,
      status: TechnologyStatus.planned,
      summary: 'Fibra multimodo.',
    ),
    SosTechnology(
      id: 'opt_cwdm',
      name: 'CWDM',
      category: TechnologyCategory.optical,
      status: TechnologyStatus.planned,
      summary: 'Multiplexacao coarse.',
    ),
    SosTechnology(
      id: 'opt_dwdm',
      name: 'DWDM',
      category: TechnologyCategory.optical,
      status: TechnologyStatus.planned,
      summary: 'Multiplexacao densa.',
    ),
    SosTechnology(
      id: 'opt_coherent',
      name: 'Coherent Optical Communication',
      category: TechnologyCategory.optical,
      status: TechnologyStatus.planned,
      summary: 'Comunicacao optica coerente de alta taxa.',
    ),
    SosTechnology(
      id: 'opt_polarization',
      name: 'Polarization Multiplexing',
      category: TechnologyCategory.optical,
      status: TechnologyStatus.planned,
      summary: 'Multiplexacao por polarizacao.',
    ),
    SosTechnology(
      id: 'opt_sdm',
      name: 'Space-Division Multiplexing (SDM)',
      category: TechnologyCategory.optical,
      status: TechnologyStatus.experimental,
      summary: 'Multiplexacao espacial em fibras multicore.',
    ),
    SosTechnology(
      id: 'opt_fso',
      name: 'Free Space Optical',
      category: TechnologyCategory.optical,
      status: TechnologyStatus.planned,
      summary: 'Laser em espaco livre.',
    ),
    SosTechnology(
      id: 'opt_ir_fso',
      name: 'IR Free Space Optical',
      category: TechnologyCategory.optical,
      status: TechnologyStatus.planned,
      summary: 'FSO infravermelho.',
    ),
    SosTechnology(
      id: 'opt_ir_remote',
      name: 'IR Remote Control',
      category: TechnologyCategory.optical,
      status: TechnologyStatus.planned,
      summary: 'Controle remoto infravermelho.',
    ),
    SosTechnology(
      id: 'opt_irda',
      name: 'IrDA',
      category: TechnologyCategory.optical,
      status: TechnologyStatus.planned,
      summary: 'Comunicação IR ponto-a-ponto legado.',
    ),
    SosTechnology(
      id: 'opt_underwater_vlc',
      name: 'Underwater VLC',
      category: TechnologyCategory.optical,
      status: TechnologyStatus.experimental,
      summary: 'Comunicação optica subaquatica por luz visivel.',
    ),
    SosTechnology(
      id: 'opt_uv',
      name: 'UV Communication',
      category: TechnologyCategory.optical,
      status: TechnologyStatus.experimental,
      summary: 'Comunicacao ultravioleta.',
    ),
    SosTechnology(
      id: 'opt_thz',
      name: 'Terahertz Wireless',
      category: TechnologyCategory.optical,
      status: TechnologyStatus.experimental,
      summary: 'Comunicacao THz.',
    ),
    SosTechnology(
      id: 'opt_silicon_photonics',
      name: 'Silicon Photonics',
      category: TechnologyCategory.optical,
      status: TechnologyStatus.experimental,
      summary: 'Integracao fotonica em chips de silicio.',
    ),
    SosTechnology(
      id: 'opt_optical_switching',
      name: 'Optical Switching',
      category: TechnologyCategory.optical,
      status: TechnologyStatus.experimental,
      summary: 'Comutacao optica de alta velocidade.',
    ),
    SosTechnology(
      id: 'opt_qkd_fiber',
      name: 'QKD via Fibra',
      category: TechnologyCategory.optical,
      status: TechnologyStatus.experimental,
      summary: 'Distribuicao quantica de chaves.',
    ),
    SosTechnology(
      id: 'opt_quantum_repeaters',
      name: 'Quantum Repeaters',
      category: TechnologyCategory.optical,
      status: TechnologyStatus.experimental,
      summary: 'Extensao de redes quanticas e QKD.',
    ),
    SosTechnology(
      id: 'audio_voip',
      name: 'VoIP',
      category: TechnologyCategory.audio,
      status: TechnologyStatus.planned,
      summary: 'Voz sobre IP.',
      protocols: ['SIP', 'RTP'],
    ),
    SosTechnology(
      id: 'audio_webrtc',
      name: 'WebRTC',
      category: TechnologyCategory.audio,
      status: TechnologyStatus.supported,
      summary: 'WebRTC completo com audio, video e data channels.',
      protocols: ['SDP', 'ICE', 'STUN', 'TURN'],
      platforms: ['mobile', 'desktop', 'web'],
    ),
    SosTechnology(
      id: 'audio_asr',
      name: 'ASR',
      category: TechnologyCategory.audio,
      status: TechnologyStatus.planned,
      summary: 'Reconhecimento de fala.',
    ),
    SosTechnology(
      id: 'audio_tts',
      name: 'TTS',
      category: TechnologyCategory.audio,
      status: TechnologyStatus.planned,
      summary: 'Sintese de fala.',
    ),
    SosTechnology(
      id: 'protocol_tcp',
      name: 'TCP',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.supported,
      summary: 'Transporte confiavel.',
    ),
    SosTechnology(
      id: 'protocol_udp',
      name: 'UDP',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.supported,
      summary: 'Transporte nao confiavel via broadcast/multicast local.',
    ),
    SosTechnology(
      id: 'protocol_quic',
      name: 'QUIC',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.planned,
      summary: 'Transporte sobre UDP.',
    ),
    SosTechnology(
      id: 'protocol_ipv4',
      name: 'IPv4',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.supported,
      summary: 'Camada IP.',
    ),
    SosTechnology(
      id: 'protocol_ipv6',
      name: 'IPv6',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.planned,
      summary: 'Camada IP moderna.',
    ),
    SosTechnology(
      id: 'protocol_mqtt',
      name: 'MQTT',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.supported,
      summary: 'Mensageria IoT via broker local (MQTT).',
    ),
    SosTechnology(
      id: 'protocol_coap',
      name: 'CoAP',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.supported,
      summary: 'Mensageria IoT via servidor CoAP local.',
    ),
    SosTechnology(
      id: 'protocol_opcua',
      name: 'OPC UA',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.planned,
      summary: 'Industrial M2M.',
    ),
    SosTechnology(
      id: 'protocol_sip',
      name: 'SIP',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.planned,
      summary: 'Sinalizacao VoIP.',
    ),
    SosTechnology(
      id: 'protocol_rtp',
      name: 'RTP',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.planned,
      summary: 'Midia VoIP.',
    ),
    SosTechnology(
      id: 'protocol_http',
      name: 'HTTP/HTTPS',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.supported,
      summary: 'Web/API.',
    ),
    SosTechnology(
      id: 'protocol_dns',
      name: 'DNS',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.planned,
      summary: 'Resolucao de nomes.',
    ),
    SosTechnology(
      id: 'protocol_arp',
      name: 'ARP',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.planned,
      summary: 'Resolucao de enderecos na LAN.',
    ),
    SosTechnology(
      id: 'protocol_dhcp',
      name: 'DHCP',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.planned,
      summary: 'Atribuicao dinamica de IP.',
    ),
    SosTechnology(
      id: 'protocol_igmp',
      name: 'IGMP',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.planned,
      summary: 'Gerenciamento de grupos multicast.',
    ),
    SosTechnology(
      id: 'protocol_vlan',
      name: 'VLAN (802.1Q)',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.planned,
      summary: 'Segmentacao de rede em LAN.',
    ),
    SosTechnology(
      id: 'protocol_stp',
      name: 'STP (802.1D)',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.planned,
      summary: 'Spanning Tree Protocol.',
    ),
    SosTechnology(
      id: 'protocol_rstp',
      name: 'RSTP (802.1w)',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.planned,
      summary: 'Rapid Spanning Tree Protocol.',
    ),
    SosTechnology(
      id: 'protocol_lacp',
      name: 'LACP (802.1AX)',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.planned,
      summary: 'Agregacao de links em LAN.',
    ),
    SosTechnology(
      id: 'protocol_qos',
      name: 'QoS (802.1p)',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.planned,
      summary: 'Priorizacao de trafego em LAN.',
    ),
    SosTechnology(
      id: 'protocol_sctp',
      name: 'SCTP',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.planned,
      summary: 'Transporte orientado a mensagens.',
    ),
    SosTechnology(
      id: 'protocol_rpl',
      name: 'RPL',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.planned,
      summary: 'Roteamento para redes de baixa potencia.',
    ),
    SosTechnology(
      id: 'protocol_lwm2m',
      name: 'LwM2M',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.planned,
      summary: 'Gerenciamento leve de dispositivos IoT.',
    ),
    SosTechnology(
      id: 'protocol_ims',
      name: 'IMS',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.planned,
      summary: 'IP Multimedia Subsystem (VoLTE/VoNR).',
    ),
    SosTechnology(
      id: 'protocol_rtmp',
      name: 'RTMP',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.planned,
      summary: 'Streaming de midia em tempo real.',
    ),
    SosTechnology(
      id: 'protocol_hls',
      name: 'HLS',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.planned,
      summary: 'Streaming segmentado via HTTP.',
    ),
    SosTechnology(
      id: 'protocol_amqp',
      name: 'AMQP',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.planned,
      summary: 'Mensageria intermediada.',
    ),
    SosTechnology(
      id: 'protocol_smtp',
      name: 'SMTP',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.planned,
      summary: 'Transporte de email.',
    ),
    SosTechnology(
      id: 'protocol_pop3',
      name: 'POP3',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.planned,
      summary: 'Recebimento de email.',
    ),
    SosTechnology(
      id: 'protocol_imap',
      name: 'IMAP',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.planned,
      summary: 'Sincronizacao de email.',
    ),
    SosTechnology(
      id: 'protocol_aodv',
      name: 'AODV',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.planned,
      summary: 'Roteamento ad-hoc sob demanda.',
    ),
    SosTechnology(
      id: 'protocol_babel',
      name: 'Babel',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.planned,
      summary: 'Roteamento para malhas dinamicas.',
    ),
    SosTechnology(
      id: 'protocol_sonet_sdh',
      name: 'SONET/SDH',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.planned,
      summary: 'Transporte optico tradicional.',
    ),
    SosTechnology(
      id: 'protocol_otn',
      name: 'OTN',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.planned,
      summary: 'Optical Transport Network.',
    ),
    SosTechnology(
      id: 'protocol_scada_ems',
      name: 'SCADA/EMS',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.planned,
      summary: 'Supervisao e controle de energia.',
      protocols: ['Modbus', 'DNP3', 'IEC 60870-5-104'],
    ),
    SosTechnology(
      id: 'protocol_bpv7',
      name: 'Bundle Protocol v7 (DTN)',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.supported,
      summary: 'DTN implementado com store-and-forward e custody.',
      protocols: ['BPv7', 'LTP'],
      platforms: ['mobile', 'desktop', 'server', 'java'],
    ),
    SosTechnology(
      id: 'protocol_ltp',
      name: 'Licklider Transmission Protocol (LTP)',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.planned,
      summary: 'Transporte para enlaces espaciais e intermitentes.',
    ),
    SosTechnology(
      id: 'protocol_rfc5444',
      name: 'MANET Packet/Message Format (RFC 5444)',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.planned,
      summary: 'Formato de mensagens para roteamento MANET.',
    ),
    SosTechnology(
      id: 'protocol_olsrv2',
      name: 'OLSRv2 (MANET)',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.planned,
      summary: 'Roteamento proativo para redes ad-hoc.',
    ),
    SosTechnology(
      id: 'protocol_oscore',
      name: 'OSCORE',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.supported,
      summary: 'Object Security for ConstrainedRESTful Environments implementado.',
      protocols: ['OSCORE', 'AES-CCM'],
      platforms: ['mobile', 'desktop', 'server', 'java'],
    ),
    SosTechnology(
      id: 'protocol_edhoc',
      name: 'EDHOC',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.supported,
      summary: 'Ephemeral Diffie-Hellman Over COSE implementado.',
      protocols: ['EDHOC', 'ECDH'],
      platforms: ['mobile', 'desktop', 'server', 'java'],
    ),
    SosTechnology(
      id: 'protocol_cbor',
      name: 'CBOR',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.supported,
      summary: 'Concise Binary Object Representation implementado.',
      protocols: ['CBOR', 'RFC 8949'],
      platforms: ['mobile', 'desktop', 'server', 'java'],
    ),
    SosTechnology(
      id: 'protocol_cose',
      name: 'COSE',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.supported,
      summary: 'CBOR Object Signing and Encryption implementado.',
      protocols: ['COSE', 'RFC 8152'],
      platforms: ['mobile', 'desktop', 'server', 'java'],
    ),
    SosTechnology(
      id: 'protocol_mls',
      name: 'MLS (Messaging Layer Security)',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.planned,
      summary: 'Seguranca para grupos de mensagens.',
    ),
    SosTechnology(
      id: 'protocol_cap',
      name: 'CAP (Common Alerting Protocol)',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.supported,
      summary: 'Formato padrao de alertas de emergencia (XML).',
    ),
    SosTechnology(
      id: 'protocol_libp2p',
      name: 'libp2p',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.planned,
      summary: 'Stack P2P modular.',
    ),
    SosTechnology(
      id: 'protocol_ipfs',
      name: 'IPFS',
      category: TechnologyCategory.protocol,
      status: TechnologyStatus.planned,
      summary: 'Distribuicao P2P de conteudo.',
    ),
    SosTechnology(
      id: 'nav_gps',
      name: 'GPS/GNSS',
      category: TechnologyCategory.navigation,
      status: TechnologyStatus.planned,
      summary: 'Posicionamento global.',
    ),
    SosTechnology(
      id: 'nav_glonass',
      name: 'GLONASS',
      category: TechnologyCategory.navigation,
      status: TechnologyStatus.planned,
      summary: 'GNSS russo.',
    ),
    SosTechnology(
      id: 'nav_galileo',
      name: 'Galileo',
      category: TechnologyCategory.navigation,
      status: TechnologyStatus.planned,
      summary: 'GNSS europeu.',
    ),
    SosTechnology(
      id: 'ham_aprs',
      name: 'HAM/APRS Bridge',
      category: TechnologyCategory.wan,
      status: TechnologyStatus.supported,
      summary: 'Conecta mesh SOS à rede global de radioamadores via APRS-IS',
      protocols: ['AX.25', 'APRS'],
      platforms: ['mobile', 'desktop', 'server'],
    ),
    SosTechnology(
      id: 'nav_beidou',
      name: 'BeiDou',
      category: TechnologyCategory.navigation,
      status: TechnologyStatus.planned,
      summary: 'GNSS chines.',
    ),
    SosTechnology(
      id: 'nav_navic',
      name: 'NavIC',
      category: TechnologyCategory.navigation,
      status: TechnologyStatus.planned,
      summary: 'GNSS indiano.',
    ),
    SosTechnology(
      id: 'nav_qzss',
      name: 'QZSS',
      category: TechnologyCategory.navigation,
      status: TechnologyStatus.planned,
      summary: 'GNSS japonês.',
    ),
    SosTechnology(
      id: 'nav_ils',
      name: 'ILS',
      category: TechnologyCategory.navigation,
      status: TechnologyStatus.planned,
      summary: 'Instrument Landing System.',
    ),
    SosTechnology(
      id: 'nav_dme',
      name: 'DME',
      category: TechnologyCategory.navigation,
      status: TechnologyStatus.planned,
      summary: 'Distance Measuring Equipment.',
    ),
    SosTechnology(
      id: 'broadcast_dvb_t2',
      name: 'DVB-T2',
      category: TechnologyCategory.broadcast,
      status: TechnologyStatus.planned,
      summary: 'TV digital terrestre.',
    ),
    SosTechnology(
      id: 'broadcast_isdb_t',
      name: 'ISDB-T',
      category: TechnologyCategory.broadcast,
      status: TechnologyStatus.planned,
      summary: 'TV digital terrestre.',
    ),
    SosTechnology(
      id: 'broadcast_atsc3',
      name: 'ATSC 3.0',
      category: TechnologyCategory.broadcast,
      status: TechnologyStatus.planned,
      summary: 'TV digital terrestre.',
    ),
    SosTechnology(
      id: 'broadcast_dvb_s2',
      name: 'DVB-S2/S2X',
      category: TechnologyCategory.broadcast,
      status: TechnologyStatus.planned,
      summary: 'Broadcast satelital de alta eficiencia.',
    ),
    SosTechnology(
      id: 'broadcast_dvb_rcs2',
      name: 'DVB-RCS2',
      category: TechnologyCategory.broadcast,
      status: TechnologyStatus.planned,
      summary: 'Canal de retorno satelital.',
    ),
    SosTechnology(
      id: 'emerging_backscatter',
      name: 'Backscatter',
      category: TechnologyCategory.emerging,
      status: TechnologyStatus.experimental,
      summary: 'Comunicacao por reflexao.',
    ),
    SosTechnology(
      id: 'emerging_molecular',
      name: 'Molecular Communication',
      category: TechnologyCategory.emerging,
      status: TechnologyStatus.experimental,
      summary: 'Comunicacao molecular (pesquisa).',
    ),
    SosTechnology(
      id: 'emerging_biophotonic',
      name: 'Biophotonic Communication',
      category: TechnologyCategory.emerging,
      status: TechnologyStatus.experimental,
      summary: 'Comunicacao biofotônica.',
    ),
    SosTechnology(
      id: 'emerging_gravity',
      name: 'Gravitational Wave Communication',
      category: TechnologyCategory.emerging,
      status: TechnologyStatus.experimental,
      summary: 'Comunicacao por ondas gravitacionais.',
    ),
    SosTechnology(
      id: 'emerging_plasma',
      name: 'Plasma Communication',
      category: TechnologyCategory.emerging,
      status: TechnologyStatus.experimental,
      summary: 'Comunicacao em plasma.',
    ),
    SosTechnology(
      id: 'emerging_elf',
      name: 'ELF Communication',
      category: TechnologyCategory.emerging,
      status: TechnologyStatus.experimental,
      summary: 'Comunicacao em ELF.',
    ),
  ];

  static final Map<String, SosTechnology> byId = {
    for (final tech in all) tech.id: tech,
  };
}
